language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
      - $HOME/.gradle
branches:
  only:
   - master
   - develop
   - /^release\/.*/

# Build steps
script:
  - cd server && gradle build
  - cd server && gradle test
  - mkdir build && (cd build; cmake ../cpplib)
  - make -C experimaestro-tests

