# Main language
language: java
jdk:
  - oraclejdk8

# Environment
dist: trusty # Use more recent Ubuntu
addons:
  apt:
    packages:
    - swig


# Use faster container-based builds
sudo: false

# Configuration
cache:
  directories:
      - $HOME/.gradle
branches:
  only:
   - master
   - develop
   - /^release\/.*/

# Build steps
script:
  - ./travis.sh

