language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
      - $HOME/.gradle
install:
  - apt-get install -qq swig
branches:
  only:
   - master
   - develop
   - /^release\/.*/

# Build steps
script:
  - ./travis.sh

