language: java
jdk:
  - oraclejdk8

# Use faster container-based builds

addons:
  apt:
    packages:
    - swig


sudo: false
cache:
  directories:
      - $HOME/.gradle
branches:
  only:
   - master
   - develop
   - /^release\/.*/

# Build steps
script:
  - ./travis.sh

