site_name: experimaestro
site_description: experimaestro Computer science experiments manager and scheduler
pages:
- Home: 'index.md'
- Scheduler:
    - Home: scheduler/index.md
    - "Connectors & Launchers": scheduler/connectors.md
    - Notification: scheduler/notification.md
- Manager:
    - Introduction: manager/index.md
    - JSON: manager/json.md
    - Tasks:
        - Intro: manager/tasks.md
        - Java tasks: manager/javatask.md
        - Python tasks: manager/pythontask.md
theme: readthedocs
extra_javascript:
    - jquery-ui.min.js
    - xpm.js
extra_css:
    - jquery-ui.min.css
    - xpm.css
markdown_extensions:
    - xpm