version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: |
            apt-get update
            apt-get install -y libpoco-dev git g++-8 cmake libssh-dev swig ninja-build doxygen python3-dev pkg-config
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Creating Build Files
          command: |
            cmake -GNinja -H. -Bbuild
      - run:
          name: Building
          command: |
            ninja -C build experimaestro-tests
      - run:
          name: Test
          command: |
            GTEST_FILTER="-SshTest.*" CTEST_OUTPUT_ON_FAILURE=1 ninja -C build test