version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: |
            echo 'deb http://deb.debian.org/debian stretch-backports main contrib non-free' >> /etc/apt/sources.list
            apt-get update
            apt-get -y -t stretch-backports install cmake libssh-dev
            apt-get install -y libpoco-dev git g++-8 swig ninja-build doxygen python3-dev pkg-config
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Creating Build Files
          command: |
            CC=gcc-8 CXX=g++-8 cmake -GNinja -H. -Bbuild
      - run:
          name: Building
          command: |
            ninja -C build experimaestro-tests
      - run:
          name: Test
          command: |
            GTEST_FILTER="-SshTest.*" CTEST_OUTPUT_ON_FAILURE=1 ninja -C build test