version: 2

jobs:
  build:
    docker:
      - image: "bpiwowar/experimaestro-test-main"
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: Creating Build Files
          command: |
            cmake -GNinja -H. -Bbuild
      - run:
          name: Building
          command: |
            ninja -j 2 -C build experimaestro-tests
      - run:
          name: Test
          # TODO: run SSH server to test remote calls
          command: |
            GTEST_FILTER="-SshTest.*" CTEST_OUTPUT_ON_FAILURE=1 ninja -C build test