version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y libpoco-dev cmake g++ openssl-dev swig libssh2-dev ninja'
      - run:
          name: Creating Build Files
          command: 'cmake -GNinja -H. -Bbuild'
      - run:
          name: Test
          command: 'ninja -C test'
